# Generated by Django 4.2.7 on 2023-11-19 22:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weather",
            options={"verbose_name": "weather", "verbose_name_plural": "weather"},
        ),
        migrations.AlterField(
            model_name="weather", name="conditions", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="weather",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="weather",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
