# Generated by Django 4.2.7 on 2023-11-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alter_weather_options_alter_weather_conditions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weather", name="created_at", field=models.DateTimeField(),
        ),
    ]
