# Generated by Django 4.2.7 on 2024-02-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0004_weather_address_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="solarenergy",
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
